DBCDK/solr-document-store

Jenkinsfile, document-store-service/src/main/docker/Dockerfile, document-store-service/src/main/docker/config.d/01_setup_db_env.sh, document-store-service/src/main/java/dk/dbc/search/solrdocstore/DatabaseMigrator.java, document-store-service/src/main/java/dk/dbc/search/solrdocstore/StatusBean.java, document-store-service/src/main/resources/db/migration/V1__Initial-schema.sql, document-store-service/src/test/java/dk/dbc/search/solrdocstore/BibliographicEntityIT.java, document-store-service/src/test/resources/entityTestData.sql
Initial Docker files
And Jenkinsfile build of docker image
=> Payara micro docker

service/src/main/java/dk/dbc/search/solrdocstore/BibliographicToBibliographicEntity.java, service/src/main/java/dk/dbc/search/solrdocstore/HoldingsToBibliographicEntity.java, service/src/main/resources/db/migration/V1__Initial-schema.sql, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicToBibliographicEntityIT.java, service/src/test/java/dk/dbc/search/solrdocstore/HoldingsToBibliographicEntityIT.java, service/src/test/java/dk/dbc/search/solrdocstore/JpaSolrDocStoreIntegrationTester.java, service/src/test/resources/entityTestData.sql
Entity's for b2b and h2b tabellerne.
=> H2b entity

service/pom.xml, service/src/main/docker/Dockerfile, service/src/main/java/dk/dbc/search/solrdocstore/AgencyLibraryTypeBean.java, service/src/main/java/dk/dbc/search/solrdocstore/LibraryConfig.java, service/src/main/java/dk/dbc/search/solrdocstore/openagency/libraryrules/JSONParser.java, service/src/main/java/dk/dbc/search/solrdocstore/openagency/libraryrules/LibraryRuleException.java, service/src/main/java/dk/dbc/search/solrdocstore/openagency/libraryrules/LibraryRules.java, service/src/main/java/dk/dbc/search/solrdocstore/openagency/libraryrules/LibraryRulesProxy.java, service/src/main/java/dk/dbc/search/solrdocstore/openagency/libraryrules/OpenAgencyClient.java, service/src/main/java/dk/dbc/search/solrdocstore/openagency/libraryrules/OpenAgencyConfig.java, service/src/test/java/dk/dbc/search/solrdocstore/AgencyLibraryTypeBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/AgencyLibraryTypeEntityIT.java, service/src/test/java/dk/dbc/search/solrdocstore/openagency/libraryrules/JSONParserTest.java, service/src/test/java/dk/dbc/search/solrdocstore/openagency/libraryrules/LibraryRulesProxyTest.java, service/src/test/resources/solr-doc-store-service.properties
Feel better now - this one actually tests the interpretation of Open Agency replies.
=> Us 2246 openagency Ready now.

service/src/main/java/dk/dbc/search/solrdocstore/BibliographicBean.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicBeanIT.java
Small simplification of updateHoldingsSingleRecord
=> Fixed Missing test for bibliographic update with no holdings

service/src/main/java/dk/dbc/search/solrdocstore/BibliographicBean.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicEntity.java, service/src/main/java/dk/dbc/search/solrdocstore/HoldingsItemBean.java, service/src/main/java/dk/dbc/search/solrdocstore/HoldingsItemEntity.java
=> Actually use the *Request structures in the Beans

service/src/main/java/dk/dbc/search/solrdocstore/BibliographicBean.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicToBibliographicEntity.java, service/src/main/java/dk/dbc/search/solrdocstore/EvictAll.java, service/src/main/java/dk/dbc/search/solrdocstore/HoldingsToBibliographicEntity.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicBeanIT.java
Store supercedes into database
=> B2B Persist

corepo-worker/src/main/java/dk/dbc/cloud/worker/SolrWorker.java
=> Supercedes always empty if the record is deleted

service/src/main/java/dk/dbc/search/solrdocstore/BibliographicBean.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicToBibliographicEntity.java, service/src/main/java/dk/dbc/search/solrdocstore/HoldingsToBibliographicBean.java, service/src/main/resources/db/migration/V1__Initial-schema.sql, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicToBibliographicEntityIT.java, service/src/test/java/dk/dbc/search/solrdocstore/HoldingsToBibliographicBeanIT.java, service/src/test/resources/entityTestData.sql
=> Rename B2B Columns (dead/live)

service/src/main/java/dk/dbc/search/solrdocstore/BibliographicEntity.java, service/src/main/java/dk/dbc/search/solrdocstore/HoldingsItemEntity.java
=> Lazy loading of indexkeys from holding/bibliographic tables

service/src/main/java/dk/dbc/search/solrdocstore/FrontendAPIBean.java, service/src/main/java/dk/dbc/search/solrdocstore/HoldingsItemBean.java, service/src/main/java/dk/dbc/search/solrdocstore/HoldingsItemEntity.java
Overså related holdings første gang jeg rettede API lazy loading
=> Lazy loading holdings items API fix

service/src/main/java/dk/dbc/search/solrdocstore/EnqueueService.java, service/src/main/java/dk/dbc/search/solrdocstore/QueueAsyncJob.java, service/src/main/java/dk/dbc/search/solrdocstore/QueueRulesBean.java, service/src/main/java/dk/dbc/search/solrdocstore/asyncjob/AsyncJob.java, service/src/main/java/dk/dbc/search/solrdocstore/asyncjob/AsyncJobControl.java, service/src/main/java/dk/dbc/search/solrdocstore/asyncjob/AsyncJobRunner.java, service/src/main/webapp/log.html, service/src/test/java/dk/dbc/search/solrdocstore/BeanFactoryUtil.java, service/src/test/java/dk/dbc/search/solrdocstore/QueueAsyncJobIT.java, service/src/test/java/dk/dbc/search/solrdocstore/QueueAsyncJobTest.java, service/src/test/java/dk/dbc/search/solrdocstore/QueueRulesBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/asyncjob/AsyncJobRunnerFactory.java
Moved into own class, long running queue processes
=> Long running queue processes

corepo-worker/src/main/java/dk/dbc/cloud/worker/SolrIndexer.java, corepo-worker/src/main/java/dk/dbc/cloud/worker/SolrWorker.java, service/src/main/resources/db/migration/V4__Work-Unit-Optional.sql, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/DatabaseMigratorIT.java
Support for optional  Unit and Work. If records are deleted, they're not members of units and works
=> Unit work and deleted

gui/app/actions/async_job.js, gui/app/api/index.js, gui/app/components/async_job_monitor/display_job.js, gui/app/components/async_job_monitor/extraordinary_job_presenter.js, gui/app/components/async_job_monitor/finished_jobs_presenter.js, gui/app/components/async_job_monitor/index.js, gui/app/components/async_job_monitor/subscription_button.js, gui/app/components/async_job_monitor/subscription_item.js, gui/app/components/queue-admin-gui.js, gui/app/components/queue_rules/add_queue_rule.js, gui/app/components/queue_rules/list_queue_rules.js, gui/app/queue-admin.js, gui/app/reducers/async_job.js, gui/app/sagas/admin_queue_sagas.js, gui/app/sagas/admin_queue_ws_sagas.js, gui/package.json, gui/test/async_job_action_reducer.test.js, gui/test/async_job_sagas.test.js, gui/webpack.config.js, service/src/main/java/dk/dbc/search/solrdocstore/asyncjob/AsyncJob.java, service/src/main/java/dk/dbc/search/solrdocstore/asyncjob/AsyncJobHandle.java, service/src/main/java/dk/dbc/search/solrdocstore/asyncjob/AsyncJobRunner.java, service/src/main/java/dk/dbc/search/solrdocstore/asyncjob/AsyncJobSessionHandler.java, service/src/main/java/dk/dbc/search/solrdocstore/asyncjob/AsyncJobWesocketAppender.java
Kø administrationsside viser nu ekstra data om de asynkrone jobs, såsom start/slut tidspunkt. Backend ændret til at sende denne data. Subscriptions/Unsubscriptions er gjort til en knap med højtaler ikon.
=> Us2263 final

corepo-worker/src/main/java/dk/dbc/cloud/worker/SolrWorker.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicEntity.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicEntityRequest.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicFrontendEntity.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicRetrieveBean.java, service/src/main/java/dk/dbc/search/solrdocstore/BiliographicRecordAPIBean.java, service/src/main/resources/db/migration/V9__repositoryId-with-data-run-by-hand_1.sql, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicEntityIT.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicEntityTest.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicRetrieveBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/BiliographicRecordAPIBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/DatabaseMigratorIT.java, service/src/test/java/dk/dbc/search/solrdocstore/DocumentRetrieveBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/EnqueueSupplierBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/HoldingsToBibliographicBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/QueueAsyncJobIT.java, service/src/test/resources/bibliographicUpdate.sql, service/src/test/resources/entityTestData.sql, service/src/test/resources/frontendIT.sql, solr-updater/pom.xml, solr-updater/src/test/resources/DocProducerTest/300101-23645564.json, solr-updater/src/test/resources/ITRequests/b-300000-23645564.json, solr-updater/src/test/resources/ITRequests/b-300000-23645564_deleted.json, solr-updater/src/test/resources/ITRequests/b-300010-23645564.json, solr-updater/src/test/resources/ITRequests/b-300010-23645564_deleted.json
=> Us2303 rec.repositoryId søgbar for slettede poster

service/src/main/java/dk/dbc/search/solrdocstore/AddResourceRequest.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicResource.java, service/src/main/java/dk/dbc/search/solrdocstore/ResourceBean.java, service/src/main/resources/db/migration/V17__Create_Resource.sql, service/src/test/java/dk/dbc/search/solrdocstore/BeanFactoryUtil.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicResourceIT.java, service/src/test/java/dk/dbc/search/solrdocstore/DatabaseMigratorIT.java, service/src/test/java/dk/dbc/search/solrdocstore/JpaSolrDocStoreIntegrationTester.java, service/src/test/resources/resource.sql
Added resource table for storing extra fields to be indexed along with
the bibliograhpic item. Added bean with API for storing fields, and
retrieving them.
=> Add resource table and bean with API

service/src/main/java/dk/dbc/search/solrdocstore/AddResourceRequest.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicResourceEntity.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicResourceRetrieveBean.java, service/src/main/java/dk/dbc/search/solrdocstore/DocumentRetrieveBean.java, service/src/main/java/dk/dbc/search/solrdocstore/DocumentRetrieveResponse.java, service/src/main/java/dk/dbc/search/solrdocstore/OpenAgencyEntity.java, service/src/test/java/dk/dbc/search/solrdocstore/BeanFactoryUtil.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicResourceIT.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicResourceRetrieveBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/DocumentRetrieveBeanIT.java, service/src/test/java/dk/dbc/search/solrdocstore/JpaSolrDocStoreIntegrationTester.java, solr-updater/src/test/java/dk/dbc/search/solrdocstore/updater/WorkerIT.java
=> Resource retrieve

.gitignore, monitor/pom.xml, monitor/src/main/docker/Dockerfile, monitor/src/main/docker/app.json, monitor/src/main/java/dk/dbc/search/solrdocstore/monitor/Mapper.java, monitor/src/main/java/dk/dbc/search/solrdocstore/monitor/MonitorApplication.java, monitor/src/main/java/dk/dbc/search/solrdocstore/monitor/QueueAll.java, monitor/src/main/java/dk/dbc/search/solrdocstore/monitor/Status.java, monitor/src/main/resources/pg-queue-endpoint-config.json, monitor/src/main/webapp/WEB-INF/beans.xml, monitor/src/main/webapp/WEB-INF/glassfish-web.xml, monitor/src/main/webapp/WEB-INF/web.xml, monitor/src/main/webapp/index.html, pom.xml, service/pom.xml, service/src/main/resources/pg-queue-endpoint-config.json
Add independent monitor service
Remove dependency on pg-queue-ee-diags and corresponding files from
service
=> SE-2483 Add independent monitor service

service/src/main/java/dk/dbc/search/solrdocstore/BibliographicBean.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicBeanIT.java
=> Check that only deleted records has empty index-keys

service/src/main/java/dk/dbc/search/solrdocstore/BibliographicBean.java, service/src/main/java/dk/dbc/search/solrdocstore/BibliographicToBibliographicEntity.java, service/src/test/java/dk/dbc/search/solrdocstore/BibliographicBeanIT.java
b supercedes a, oh no... wait... a supercerdes b and b is deleted
=> When live->dead gets reversed

service/src/main/java/dk/dbc/search/solrdocstore/request/BibliographicEntityRequest.java, service/src/main/java/dk/dbc/search/solrdocstore/request/HoldingsItemEntityRequest.java
A search revealed only these few places where producerVersion remained :)
=> HOL-32: Removing unused setters for producerVersion

service/src/main/java/dk/dbc/search/solrdocstore/HoldingsItemBean.java
=> Reintroduced POST of holdings-items (FFU)

db/pom.xml, emulator/pom.xml, monitor/pom.xml, pom.xml, queue/pom.xml, service/pom.xml, solr-updater/pom.xml, updater-business-logic/pom.xml
use version numbers from parrent
Keep pom.xml clean
=> Use microservice-pom:java11-old-payara5 parent

updater-business-logic/src/main/java/dk/dbc/solrdocstore/updater/businesslogic/BusinessLogic.java
Er det bare dette der skal tilføjes for FBI Info cover til SOLR?
=> add hasFBICoverUrl resource for FBIInfo
